FROM node:lts

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

# Copy the rest of the application code
COPY ./ ./

# Expose the port the application will run on
EXPOSE 3000

# Run the application
ENTRYPOINT ["npm", "run", "start", "--", "--host", "0.0.0.0"]