services:
  api:
    image: dyrits/finshark-api:latest
    build:
      context: ./api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:5018
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - ./api.csproj
        - action: rebuild
          path: ./api.csproj
    ports:
      - "5018:5018"
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FinShark_DROWSSAP_@S
      - DB_NAME=FinShark
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: